export const refs = {
  buttonRefHome: document.querySelector('#button-header-home'),
  buttonRefLibrary: document.querySelector('#button-header-library'),
  divRefButtonLibrary: document.querySelector('.header-logo--position'),
  divRefWatchedQueue: document.querySelector('.header-button__library'),
  buttonRefWatched: document.querySelector('#button-header-watched'),
  buttonRefQueue: document.querySelector('#button-header-queue'),
  filmNameRef: document.querySelector('#film-name'),
  filmVotesRef: document.querySelector('#votes'),
  filmAverageVotesRef: document.querySelector('#average-votes'),
  filmPopularityRef: document.querySelector('#popularity'),
  filmOriginalTitleRef: document.querySelector('#original-title'),
  filmGenreRef: document.querySelector('#genre'),
  filmOverviewRef: document.querySelector('#film-overview'),
  backdropRef: document.querySelector('#backdrop'),
  filmInfoCloseBtnRef: document.querySelector('.js-close'),
  filmImageRef: document.querySelector('#film-modal-image'),
  filmAddToWatchedBtnRef: document.querySelector('#js-watched'),
  filmAddToQueueBtnRef: document.querySelector('#js-queue'),
  filmWatchTrailerBtnRef: document.querySelector('#js-trailer'),
  galleryListRef: document.querySelector('#js-list'),
  formRef: document.querySelector('.header-form'),
  paginationRef: document.querySelector('#pagination'),
  watchedBtnRef: document.getElementById('js-watched'),
  queueBtnRef: document.getElementById('js-queue'),
  alertMessage: document.querySelector('.header-form--search'),
  errorSearchRef: document.querySelector('.header-form__input'),
  switchThemeRef: document.querySelector('#switch-theme'),
  arrowLinkRef: document.querySelector('.arrow-link'),

  WATCHED: 'watched',
  QUEUE: 'queue',
};
